version: 2.1

orbs:
  node: circleci/node@4.7.0 
  cypress: cypress-io/cypress@3

jobs:
  build:
    docker:
      - image: circleci/node:latest
    environment:
      CI: false
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build application
          command: npm run build
      - run: 
          name: Print Node.js version
          command: node --version
      - run: 
          name: Print npm version
          command: npm --version
        
  build-node:
    # Build node project
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - run: 
          command: npm install
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy output to artifacts dir
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
  deploy:
    # This is an example deploy job, not actually used by the workflow
    docker:
      - image: cimg/base:stable
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows: 
  version: 2
  build-and-test:
    jobs:
      - build
      - build-node:
          requires:
            - build
      - cypress/run:
          requires:
            - build
